name: Deploy WordPress Plugin to SVN

on:
  push:
    branches:
      - test
    tags:
      - "*"

env:
  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Deploy to SVN
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: bitnob
        ASSETS_DIR: ./assets

