name: Deploy to WordPress.org
on:
  push:
    branches:
    - main
jobs:
  tag:
    name: Build release and deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Deploy to WordPress.org
      uses: sultann/action-plugin-deploy@master
      with:
        svn_username: ${{ secrets.SVN_USERNAME }}
        svn_password: ${{ secrets.SVN_PASSWORD }}
        svn_slug: 'bitnob' # Remove this if GitHub repo name matches SVN slug
        dry_run: true