name: Deploy to WordPress.org
on:
  push:
    branches:
    - main
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: WordPress Plugin Deploy
      uses: nk-o/action-wordpress-plugin-deploy@master
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SOURCE_DIR: bitnob/
        SLUG: bitnob # optional, remove if GitHub repo name matches SVN slug, including capitalization